version: '3.8'

services:
  # 1. Cơ sở dữ liệu cho MLflow Metrics
  postgres_db:
    image: postgres:15-alpine
    container_name: mlflow_db
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_metadata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Object Storage thay thế AWS S3 để lưu Artifacts/Models:
  minio_s3:
    image: minio/minio:latest
    container_name: mlflow_s3
    ports:
      - "9002:9000" # API port (host 9002 -> container 9000)
      - "9003:9001" # Web UI port (host 9003 -> container 9001)
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  # 3. Tạo tự động một Bucket tên là "mlflow-bucket" trong MinIO khi khởi động
  create_bucket:
    image: minio/mc
    container_name: mlflow_create_bucket
    depends_on:
      - minio_s3
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio_s3:9000 minio_admin minio_password) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb myminio/mlflow-bucket || true;
      exit 0;
      "

  # 4. MLflow Tracking Server kết nối với DB và S3
  mlflow_server:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    container_name: mlflow_tracking_server
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
      - minio_s3
    environment:
      - AWS_ACCESS_KEY_ID=minio_admin
      - AWS_SECRET_ACCESS_KEY=minio_password
      - AWS_DEFAULT_REGION=us-east-1
      - MLFLOW_S3_ENDPOINT_URL=http://minio_s3:9000
    entrypoint: [
      "bash", "-c", 
      "pip install psycopg2-binary boto3 && mlflow server --backend-store-uri=postgresql://mlflow_user:mlflow_password@postgres_db:5432/mlflow_metadata --default-artifact-root=s3://mlflow-bucket/ --host=0.0.0.0 --port=5000"
    ]
    

volumes:
  postgres_data:
  minio_data: